### ISSUE TITLE
Configure whether a class name can be added？

### ISSUE THREAD

**Issue by awnawnawn** [francoischalifour/medium-zoom#168]
## The problem

I want to add a `class` name to switch the `background color`, because the background color should also be able to switch between **day and night modes**

## Implementation

`Options` Add `claasName` optional attributes

**Comment by ayushnix** [comment]
An option to automatically switch between dark and light background colors according to `prefers-color-scheme` would be great.

**Comment by plivox** [comment]
A trick I use with my Docusaurus documentation:

```css
:root {
  --plugin-image-zoom-background-color: #fff;
}

[data-theme='dark'] {
  --plugin-image-zoom-background-color: #1e2125;
}
```

```ts
imageZoom: {
  options: {
    background: "var(--plugin-image-zoom-background-color)",
  },
},
```
